// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_VspHSc9-JPPIX0Wf0C6bpaY5a8KSgeo',
    appId: '1:608775298230:web:4742bb2fe78da543145a17',
    messagingSenderId: '608775298230',
    projectId: 'chatapp-c5b65',
    authDomain: 'chatapp-c5b65.firebaseapp.com',
    storageBucket: 'chatapp-c5b65.appspot.com',
    measurementId: 'G-JBB73LZJXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCXiCTtVi3ELgOsgk0KFUoj1drmK5qHuQ',
    appId: '1:608775298230:android:4c96b6ada9c39d54145a17',
    messagingSenderId: '608775298230',
    projectId: 'chatapp-c5b65',
    storageBucket: 'chatapp-c5b65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXY9NAS4zQx7fewpQEv3b0QucN4YKQuHQ',
    appId: '1:608775298230:ios:d1ab8d86c61b936e145a17',
    messagingSenderId: '608775298230',
    projectId: 'chatapp-c5b65',
    storageBucket: 'chatapp-c5b65.appspot.com',
    iosClientId: '608775298230-qr5102pe0dvvsa4mg9puep124ipur95m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXY9NAS4zQx7fewpQEv3b0QucN4YKQuHQ',
    appId: '1:608775298230:ios:d1ab8d86c61b936e145a17',
    messagingSenderId: '608775298230',
    projectId: 'chatapp-c5b65',
    storageBucket: 'chatapp-c5b65.appspot.com',
    iosClientId: '608775298230-qr5102pe0dvvsa4mg9puep124ipur95m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newchat',
  );
}
